language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt541 -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install qt54base qt54websockets

script:
  - source /opt/qt54/bin/qt54-env.sh
  - qmake
  - make

env:
  global:
    - LD_LIBRARY_PATH=/opt/qt54/lib
