language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository beineri/opt-qt54 -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install qt54base qt54websockets

script:
  - qmake
  - make
