language: cpp
compiler: gcc

before_install:
  - wget -O - http://apt.mopidy.com/mopidy.gpg | sudo apt-key add -
  - sudo wget -O /etc/apt/sources.list.d/mopidy.list http://apt.mopidy.com/mopidy.list
  - sudo add-apt-repository ppa:beineri/opt-qt541 -y
  - sudo apt-get update -qq
  - sudo pip install cpp-coveralls

install:
  - sudo apt-get install mopidy screen
  - sudo apt-get install qt54base qt54websockets

script:
  - source /opt/qt54/bin/qt54-env.sh
  - qmake CONFIG+=debug
  - make
  - screen -dmS mopidy
  - ./tests/tests
  - screen -X -S mopidy quit

after_success:
  - coveralls --build-root src/ --exclude tests --exclude demos --gcov-options '\-lpr'

env:
  global:
    - LD_LIBRARY_PATH=/opt/qt54/lib:$TRAVIS_BUILD_DIR/src
