environment:
  QTDIR: C:\Qt\5.4\mingw491_32
  MINGW: C:\Qt\Tools\mingw491_32

configuration: Release

install:
  - set PATH=%PATH%;%QTDIR%\bin;%MINGW%\bin

build_script:
  - qmake -r
  - mingw32-make
